// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

const localurl = "http://20.219.114.117:35001/api/";
export const imageUploadBasUrl = 'http://20.219.114.117:35001/';
export const environment = {
  production: false,
  AdminGroup: {
    "GroupName": "Admin",
    "GroupId": 2
  },
  login: localurl + "v1/adminlogin",
  states: localurl + "v1/getStateWithCity",
  allStates: localurl + "v1/getAllState",
  allCities: localurl + "v1/getAllCity",
  cityByStates: localurl + "v1/getCityByStateId",
  createcustomer: localurl + "v1/customer/CreateCustomer",
  updatecustomer: localurl + "v1/customer/updateCustomer",
  getAllCustomer: localurl + "v1/customer/getCustomer",
  deleteCustomer: localurl + "v1/customer/deleteCustomer/",
  getCustomerById: localurl + "v1/customer/getSingleCustomer",
  createoffice: localurl + "v1/officeAdmin/createOfficeAdmin",
  updateoffice: localurl + "v1/officeAdmin/updateOfficeAdmin/",
  getalloffice: localurl + "v1/officeAdmin/getOfficeAdmin",
  deleteoffice: localurl + "v1/officeAdmin/deleteOfficeAdmin/",
  getofficebyid: localurl + "v1/officeAdmin/getSingleOfficeAdmin/",
  createdeliveryboy: localurl + "v1/CreateDeliveryBoyDetails",
  getalldeliveryboy: localurl + "v1/getDeliveryBoyDetails",
  deletedeliveryboy: localurl + "v1/deleteDeliveryBoyDetails/",
  getdeliveryboybyid: localurl + "v1/getSingleDeliveryBoyDetails/",
  updatedeliveryboy: localurl + "v1/updateDeliveryBoyDetails",
  createdocket: localurl + "v1/docket/CreateDocketDetails",
  getalldocket: localurl + "v1/docket/getDocketDetails",
  deletedocket: localurl + "v1/docket/deleteDocket/",
  getdocketbyid: localurl + "v1/docket/SearchDocketDetailsByDocketId",
  updatedocket: localurl + "v1/docket/updateDocket",
  getdocketbystatus: localurl + "v1/SearchDocketByStatus/status",
  createAddress: localurl + "v1/CreateAddress",
  updateAddress: localurl + "v1/updateAddress/",
  getAllDocketStatus: localurl + "v1/getAllStatus",
  createPickup: localurl + "v1/createPickupDetails",
  updatePickup: localurl + "v1/updatePickupDetails/",
  getAllPickup: localurl + "v1/getPickupDetails",
  getPickupByRequestId: localurl + "v1/getpickageDetailsByRequestId",
  getAllContents: localurl + "v1/getAllContents",
  createPackageDetails: localurl + "v1/createPackageDetails",
  getPackageDetailsByRequest: localurl + "v1/getpackageDetailsByRequesteId",
  deletePackageDetailsByRequest: localurl + "v1/deletepackageDetails/",
  getAllModeType: localurl + 'v1/getAllmode',
  getManifesthById: localurl + 'v1/SingleMenifestDetails',
  getAllManifest: localurl + 'v1/getMenifestDetails',
  updateManifestDetails: localurl + 'v1/updateMenifestDetails',
  createManifestDetails: localurl + 'v1/CreateMenifestDetails',
  deleteManifestDeails: localurl + 'v1/deleteMenifestDetails/',
  createVehicleDetails: localurl + 'v1/CreateVehicalDetails',
  deleteVehicalDetailsByManifest: localurl + 'v1/deleteVehicalDetailsByMenifestId/',
  getVehicalDetailsByManifest: localurl + 'v1/getVehicalDetailsByMenifestId',
  createDriverDetails: localurl+ "v1/CreateDriverDetails",
  deleteDriverDetailsByManifest: localurl + 'v1/deleteDriverDetailsByMenifestId/',
  getDriverDetailsByManifest: localurl + 'v1/getDriverDetailsByMenifestId',
  createMenifestByAirMode: localurl + 'v1/createmenifestbymode',
  deleteMenifestbyAirMode: localurl + 'v1/deletemenifestbymode/',
  createMenifestByRailMode: localurl + 'v1/createmenifestbytrain',
  deleteMenifestByRailMode: localurl + 'v1/deletemenifestbytrain/',
  createMenifestByRoadMode: localurl + 'v1/createmenifestbyroad',
  deleteMenifestByRoadMode: localurl + 'v1/deletemenifestbyroad/',
  createPickupAllocation: localurl + 'v1/CreateAllocation',
  deletePickupAllocation: localurl + 'v1/deleteAllocationbyAllocationId/',
  getAllInscan: localurl + 'v1/getInscanDetails',
  createInscan: localurl + 'v1/CreateInscanDetails',
  updateInscan: localurl + 'v1/updateInscanDetailsByInscanId',
  getInscanById: localurl + 'v1/getSingleInscanDetailsInscanId',
  getAllMapDocketMenifest: localurl + 'v1/getAllMenifestDocketMappingByMenifestId',
  cretateDocketMenifestMap: localurl + 'v1/CreateMenifestDocketMapping',
  deleteDocketMenifestMap: localurl + 'v1/deleteMenifestDocketMappingByuniqueId/',
  getDRSDetails: localurl + 'v1/DRS/getDRSDetails',
  createDRSDetails: localurl + 'v1/DRS/createDRSDetails',
  updateDRSDetails: localurl + 'v1/DRS/updateDRSDetails',
  getSingleDRSDetails: localurl + 'v1/DRS/getSingleDRSDetails',
  deleteDRSDetails: localurl + 'v1/DRS/deleteDRSDetails/',
  getAllMapDocketDrs: localurl + 'v1/getAllDocketDRSMappingByDRSId',
  createDocketDrsMap: localurl + 'v1/CreateDocketDRSMapping',
  deleteDocketDrsMap: localurl + 'v1/deleteDocketDRSMappingByDocketDRSId/',
  createPOD: localurl + 'v1/createPodDetails',
  getPOD: localurl + 'v1/getPodDetails',
  updatePOD: localurl + 'v1/updatePodDetails',
  deletePOD: localurl + 'v1/deletePODDetails/',
  getPODdetailsById: localurl + 'v1/getPodDetailsByPodId',
  getBillingDetails: localurl + 'v1/billing/getBillingDetails',
  createBillingDetails: localurl + 'v1/billing/CreateBillingDetails',
  updateBillingDetails: localurl + 'v1/billing/updateBillingDetails',
  deleteBillingDetails: localurl + 'v1/billing/deleteBillingDetails/',
  getSingleBillingDetails: localurl + 'v1/billing/getSingleBillingDetails',
  addBillingItems: localurl + 'v1/AddbillingItems',
  deleteBillingItems: localurl + 'v1/deleteBillingItemDetails/',
  getBillingItemByInvoiceId: localurl + 'v1/getAllbillingItembyInvoiceId',
  getHSNCodes: localurl + 'v1/getHSNcodeDetails',
  getAllMapDocketBill: localurl + 'v1/getAllBillingbyDocketMapping',
  cretateDocketBillMap: localurl + 'v1/CreateBillingbyDocketMapping',
  deleteDocketBillMap: localurl + 'v1/deleteBillingbyDocketSMappingByDocketBillingId/',
  addpodproofimage: localurl + 'v1/addImageInPod/PodImage',
  deletepodproofimage: localurl + 'v1/deletePodImageByPodImgId/',
  getpodproofimage: localurl + 'v1/getPodImageByPodID',
  drssearch: localurl + 'v1/DRS/SearchDRSDetailsByDRSField',
  drssearchrange: localurl + 'v1/DRS/getDRSdatawithrange',
  menifestsearch: localurl + 'v1/SearchMenifestDetailsByMenifestfield',
  menifestsearchrange: localurl + 'v1/getdatawithrange',
  inscansearchbydate: localurl + 'v1/SearchInscanDetailsByDispatchDate',
  inscansearch: localurl + 'v1/SearchInscanDetailsByInscanField',
  updateProfile: localurl + 'v1/updateAdminDetails',
  getAdminByEmail: localurl + 'v1/getAdminDetailByEmail',
  getTodaysGeneratedDocketDetails: localurl +  'v1/docket/getTodaysGeneratedDocketDetails',
  getDocketDetailsByDocketStatus: localurl + 'v1/docket/getDocketDetailsByDocketStatus',
  SearchDocketDetailsByDocketId: localurl + 'v1/docket/SearchDocketDetailsByDocketId',
  getpickupdateilsbyfiedl: localurl + 'v1/getpickageDetailsByfield',
  getpickupdateilsbydate: localurl + 'v1/getpickageDetailsBydate',
  getpickageDetailsByPending: localurl + 'v1/getpickageDetailsByPending',
  getpickageDetailsByAllocated: localurl + 'v1/getpickageDetailsByAllocated',
  searchDocketDetailsByDocketStatus: localurl + 'v1/docket/searchDocketDetailsByDocketStatus',
  getAllUser: localurl + 'v1/user/getAllUser',
  deleteUser: localurl + 'v1/user/deleteUserDetails/',
  updateUserStatus: localurl + 'v1/user/updateUserAccountStatus',
  getAllBanner: localurl + 'v1/banner/getAllBannerDetails',
  deleteBanner: localurl + 'v1/banner/deleteBannerDetails/',
  createBanner: localurl + 'v1/banner/CreateBannerDetails',
  updateBanner: localurl + 'v1/banner/updateBannerDetails',
  getBannerById: localurl + 'v1/banner/getSingleBannerDetails/',
  getAllCourseCategory: localurl + 'v1/Category/getAllCourseCategory',
  createCourseCategory: localurl + 'v1/Category/CreateCourseCategoryDetails',
  updateCourseCategory: localurl + 'v1/Category/updateCourseCategoryDetails',
  deleteCourseCategory: localurl + 'v1/Category/deleteCourseCategoryDetails/',
  getCourseCategoryById: localurl + 'v1/Category/getSingleCourseCategoryDetails/',
  getAllCourseSubCategory: localurl + 'v1/SubCategory/getAllCourseSubCategory',
  createCourseSubCategory: localurl + 'v1/SubCategory/CreateCourseSubCategoryDetails',
  updateCourseSubCategory: localurl + 'v1/SubCategory/updateCourseSubCategoryDetails',
  deleteCourseSubCategory: localurl + 'v1/SubCategory/deleteCourseSubCategoryDetails/',
  getCourseSubCategoryById: localurl + 'v1/SubCategory/getSingleCourseSubCategoryDetails/',
  getAllCourseDetails: localurl + 'v1/Course/getAllCourseDetails',
  createCourseDetails: localurl + 'v1/Course/CreateCourseDetails',
  updateCourseDetails: localurl + 'v1/Course/updateCourseDetails',
  deleteCourseDetails: localurl + 'v1/Course/deleteCourseDetails/',
  getCourseDetailById: localurl + 'v1/Course/getSingleCourseDetails/',
  getAllLessonDetails: localurl + 'v1/lession/getAlllessionDetails',
  createLessonDetails: localurl + 'v1/lession/CreatelessionDetails',
  updateLessonDetails: localurl + 'v1/lession/updatelessionDetails',
  deleteLessonDetails: localurl + 'v1/lession/deletelessionDetails/',
  getLessonDetailsById: localurl + 'v1/lession/getSinglelessionDetails/',
  userlogin: localurl + 'v1/admin/Adminlogin',
  getAllQuiz: localurl + 'v1/Quiz/getAllQuiz',
  getQuizDetailsById: localurl + 'v1/Quiz/getSingleQuizDetails',
  deleteQuizDetails: localurl + 'v1/Quiz/deleteQuizDetails/',
  updateQuizDetails: localurl + 'v1/Quiz/updateQuizDetails',
  addQuizDetails: localurl + 'v1/Quiz/AddQuizDetails',
  createQuizQuestion: localurl + 'v1/QuizQuestion/CreateQuizQuestionDetails',
  updateQuizQuestion: localurl + 'v1/QuizQuestion/updateQuizQuestionrDetails',
  getQuizQuestionDetailsById: localurl + 'v1/QuizQuestion/getSingleQuizQuestionDetails/',
  getAllQuizQuestion: localurl + 'v1/QuizQuestion/getAllQuizQuestionbyQuizId',
  getAllEnrollment: localurl + 'v1/Enrollment/getAllEnrollmentDetails',
  updateEnrollment: localurl + 'v1/Enrollment/updateEnrollmentDetails',
  deleteEnrollment: localurl + 'v1/Enrollment/deleteEnrollmentDetails/',
  resetPassword: localurl + 'v1/admin/resetPasswordforAdmin',
  displayAllUser: localurl + 'v1/getUser',
  getQuizScoreByUser: localurl + 'v1/Score/getAllscorebyQuizAndUserId',
  commonAddFile: localurl + 'v1/addImage',
  deleteBannerFile: localurl + 'v1/deletebannerfile/',
  courseAddFile: localurl + 'v1/addCoureseImage',
  deleteCourseFile: localurl + 'v1/deleteCoursefile/',
  lessionAddFile: localurl + 'v1/addlessonImage',
  deleteLessionFile: localurl + 'v1/deletelessonfile/'
};
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
